name: Coinone-Alarm

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  alarm:
    name: Coinone
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Alarm
        env:
          COINONE_ACCESS_TOKEN: ${{ secrets.COINONE_ACCESS_TOKEN }}
          COINONE_SECRET_KEY: ${{ secrets.COINONE_SECRET_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: |
          bin/rails runner lib/coinone.rb
