name: Coinone-Alarm

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  alarm:
    name: Coinone
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: Gemfile

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Alarm
        env:
          COINONE_ACCESS_TOKEN: ${{ secrets.COINONE_ACCESS_TOKEN }}
          COINONE_SECRET_KEY: ${{ secrets.COINONE_SECRET_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_BOT_CHANNEL_ID: ${{ secrets.TELEGRAM_BOT_CHANNEL_ID }}
        run: |
          bin/rails runner lib/coinone.rb
